# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: push

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  # compile the latex document
  build-latex:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # compile the document using texlive and latexmk
    - name: Compile LaTeX document
      uses: xu-cheng/latex-action@master
      with:
        root_file: main.tex
        working_directory: docs

    # Store the compiled pdf as an artifact
    - uses: actions/upload-artifact@v1
      with:
        name: documentation
        path: docs/main.pdf

  # run unit tests
  unit-tests:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Octave
      run: |
        sudo apt-get -y -qq install octave

    - name: Install MOxUnit
      run: |
        git clone https://github.com/MOxUnit/MOxUnit.git
        cd MOxUnit
        make install
        cd ..

    - name: Perform unit tests
      run: |
        octave --no-gui --eval "addpath(strcat(pwd(),'/src');moxunit_set_path;moxunit_runtests('./tests')"
